// employee-dashboard/src/components/LoginModal.jsx
import { useContext, useState } from "react"
import StoreContext from "../store/StoreContext"
import { client } from "../services/client"
import toast from "react-hot-toast"
import Modal from "./Modal"
import InputField from "./InputField"

const LoginModal = ({show, onLoggedIn}) => {

    const ctx = useContext(StoreContext)

    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')

    const onLogin = (e) => {
        e.preventDefault()

        const login = client.post('/auth/login', { email, password })

        toast.promise(login, {
            loading: 'Loggin in...',
            success: (res) => {
                const { token, user } = res.data 
                ctx.setToken(token)
                ctx.setUser(user)
                client.defaults.headers.common['Authorization'] = `Bearer ${token}`
                
                setPassword('')
                onLoggedIn()
                return `Logged in successfully`
            },
            error: e => {
                console.error('login error', e)
                return `Error logging in user!\n${e.response?.data?.detail || e.message}`
            }
        })
    }

    return (
        <Modal show={show} title="Employee Login" dark={true} closable={false}>
            <form action="" method="post" onSubmit={onLogin}>
                <InputField name="email" label="Email" required={true} value={email} onChange={e => setEmail(e.target.value)} />
                <InputField name="password" type="password" label="Password" autoComplete="off" required={true} value={password} onChange={e => setPassword(e.target.value)} />
                <div className="mt-6">
                    <button className="bg-blue-400 rounded-md hover:bg-blue-500 px-6 py-1.5 text-white">Login</button>
                </div>
            </form>
        </Modal>
    )
}

export default LoginModal

// hr-dashboard/src/components/LoginModal.vue
<script setup>
import { ref } from 'vue';
import { client } from '../services/client';
import { toast } from 'vue3-toastify';
import { useStore } from '../store';
import Modal from './Modal.vue';
import FormField from './FormField.vue';

const store = useStore()

const emit = defineEmits(['close-modal'])
const { show } = defineProps({
    show: Boolean
})

const email = ref('')
const password = ref('')

const login = () => {
    const loginToast = toast.loading('Logging in...', { theme: toast.THEME.COLORED, position: toast.POSITION.TOP_CENTER, transition: toast.TRANSITIONS.FLIP })
    client.post('/auth/login', {
        email: email.value,
        password: password.value
    })
        .then(res => {
            const user = res.data.user
            const token = res.data.token
            store.auth.user = user
            store.auth.token = token
            client.defaults.headers.common['Authorization'] = `Bearer ${token}`
            // console.log(res)

            //Other resources
            store.setResources()

            password.value = ''
            toast.update(loginToast, { type: 'success', autoClose: 2000, isLoading: false, render: 'Logged in successfully' })
            emit('close-modal')
        })
        .catch(e => {
            console.error(e)
            toast.update(loginToast, {
                type: 'error', autoClose: 2000, isLoading: false,
                render: `Error logging in\n${e.response?.data?.detail || e.message}`
            })
        })
        .finally()
}

</script>
<template>
    <Modal title="HR Login" @close-modal="emit('close-modal')" :show="show" :darkBackdrop="true" :closable="false">
        <form method="post" @submit.prevent="login">
            <div class="flex flex-col mt-8">
                <FormField name="email" label="Email" v-model="email" />
                <FormField name="password" label="Password" type="password" v-model="password" autocomplete="off" />
                <div class="flex mb-6">
                    <button
                        class="cursor-pointer bg-green-500 hover:bg-green-600 text-white rounded-md px-14 py-2 text-xl">Login</button>
                </div>
            </div>
        </form>
    </Modal>
</template>
