// employee-dashboard/src/components/Modal.jsx
import { createPortal } from "react-dom"

import { XCircleIcon } from "@heroicons/react/24/outline"
import Card from "./Card"


const Backdrop = (props) => {
    const { onClose, dark } = props
    return createPortal(
        (<div className={`fixed top-0 left-0 w-[100vw] h-[100vh] ${dark ? 'bg-[rgba(10,10,10,.95)] backdrop-blur-md': 'bg-[rgba(200,200,200,0.15)]'}`} onClick={onClose}> 
    </div>),
    document.querySelector('#backdrops-container')
    ) 
}

const Overlay = (props) => {
    const { children, onClose, title, closable } = props

    return createPortal(
        <Card className="w-[95%] md:w-[75%] left-[50%] top-6 fixed p-6 transform-[translateX(-50%)] max-h-[95vh] overflow-y-auto">
        <h4 className="font-bold mb-6 flex justify-between text-xl"><span>{title}</span> {closable && <button className="cursor-pointer" onClick={onClose}><XCircleIcon className="size-12 stroke-red-400" /></button>}</h4>
        { children }
        </Card>,
        document.getElementById('modals-container')
    )
}

const Modal =  (props) => {

    const { title, children, onClose, show, dark=false, closable=true  } = props

    const close = e => {
        if(!closable) return 
        onClose(e)
    }

    return (show ? <>
        <Backdrop onClose={close} dark={dark} />
        <Overlay onClose={close} title={title} closable={closable} >{ children }</Overlay>
        </>: <></>)
}

export default Modal

// hr-dashboard/src/components/Modal.vue
<script setup>
import Card from './Card.vue';
import { Teleport } from 'vue';
import { XCircleIcon } from '@heroicons/vue/24/outline';

const emit = defineEmits(['close-modal'])

const { show, title, darkBackdrop, closable } = defineProps({
    show: { type: Boolean, default: false },
    title: { type: String, default: 'Title' },
    darkBackdrop: { type: Boolean, default: false },
    closable: { type: Boolean, default: true }
})

const onCloseModal = () => {
    if (closable)
        emit('close-modal')
}
</script>

<template>
    <Teleport to=".modal-container">
        <div v-if="show" @click.self="onCloseModal"
            :class="darkBackdrop ? 'bg-[rgba(5,5,5,0.9)] backdrop-blur-md' : 'bg-[rgba(55,55,55,0.1)]'"
            class="fixed z-40 w-[100vw] h-[100vh] transform-[translate(-50%, -50%)]">
            <Card
                class="w-[95%] md:w-[75%] min-h-45 max-h-[95vh] px-4 py-2 md:px-12 md:py-4 overflow-y-scroll absolute top-4 left-1/2 transform-[translateX(-50%)]">
                <h2 class="flex justify-between mb-2 text-xl font-bold">
                    <span>{{ title }}</span>
                    <button class="cursor-pointer" @click="onCloseModal" v-if="closable">
                        <XCircleIcon class="size-12 stroke-red-400" />
                    </button>
                </h2>
                <slot />
            </Card>
        </div>
    </Teleport>
</template>
