// employee-dashboard/src/components/PublicHoliday.jsx
import { formatDate } from "../utils"

const PublicHoliday = (props) => {

    const { name, date, remarks } = props

    return (
        <div className="rounded-md bg-blue-200 py-1.5 px-3.5 text-sm flex justify-between mb-2">
            <span className="font-semibold flex-1/3">{ name }</span>
            <span className="font-light flex-1/3">{ remarks }</span>
            <span className="font-semibold">{ formatDate(date) }</span>
        </div>
    )
}

export default PublicHoliday

// hr-dashboard/src/components/PublicHoliday.vue
<script setup>
import { formatDate } from '../utils';
const { name, date, type } = defineProps({
    name: String,
    date: String,
    type: { type: String, default: 'Public Holiday' }
})


</script>
<template>
    <div class="rounded-md flex text-sm p-2"
        :class="type.trim().toLowerCase().startsWith('optional') ? 'bg-gray-100' : 'bg-green-100'">
        <div class="flex-1 font-bold">{{ name }}</div>
        <div class="flex-1 ">{{ type }}</div>
        <div class="flex-1 font-bold text-right" v-html="formatDate(date)"></div>
    </div>
</template>
