// hr-dashboard/src/components/StatusChip.vue
<script setup>
const { status } = defineProps({
    status: String,
})

const colors = {
    'approved': '#D5F4DC',
    'pending': '#E3E3E3',
    'declined': '#F3E6D6',
    'cancelled': '#F4D5D5'
}
</script>
<template>
    <div class="rounded-sm w-24 text-center px-2 py-1"
        :style="{ backgroundColor: colors[status.toLowerCase()] || '#E3E3E3' }">
        {{ status }}
    </div>
</template>

// employee-dashboard/src/components/StatusChip.jsx
const getChipColor = status => {
    if(status == 'Pending') return 'bg-gray-300'
    if(status == 'Approved') return 'bg-green-300'
    if(status == 'Declined') return 'bg-amber-300'
    if(status == 'Cancelled') return 'bg-red-300'
}


const StatusChip = (props) => {
    return (
        <div className={`px-0.5 sm:px-2 py-1 rounded-md sm:w-26 text-sm text-center 
        ${getChipColor(props.status)}`}>
            { props.status }
        </div>
    )
}

export default StatusChip
