// hr-dashboard/src/App.vue
<script setup>
import { ref } from 'vue';
import { useStore } from './store';
import NavButton from './components/NavButton.vue';
import Button from './components/Button.vue';
import { PlusIcon } from '@heroicons/vue/24/outline';
import Profile from './components/Profile.vue';
import AddEmployeeModal from './components/AddEmployeeModal.vue';

import { RouterView, useRoute } from 'vue-router';

const store = useStore()
const route = useRoute()

const showAddEmployeeModal = ref(false)

</script>

<template>
  <div class="bg-green-100 py-2 px-12 relative">
    <AddEmployeeModal :show="showAddEmployeeModal" @close-modal="showAddEmployeeModal = false" />
    <div class="flex justify-between items-center">
      <div class="h-12"><img src="/favicon.svg" alt="Logo" class="h-full"></div>
      <div class="flex gap-6.5 items-stretch self-stretch my-[-8px]">
        <NavButton label="Home" href="/" :active="route.name == 'home'" />
        <NavButton label="Calendar" href="/calendar" :active="route.name == 'calendar'" />
        <NavButton label="Leave" :href="{ name: 'leave' }" :active="route.name == 'leave'" />
        <NavButton label="Reports" :href="{ name: 'reports' }" :active="route.name == 'reports'" />
      </div>
      <div>
        <Profile :user="store.auth.user" />
      </div>
    </div>
  </div>
  <div class="bg-green-200 py-6 px-12 h-[180px]">
    <h2 class="text-4xl font-semibold flex justify-between"><span>Dashboard</span>
      <Button label="Add Employee" @click="showAddEmployeeModal = true">
        <PlusIcon class="size-6" />
      </Button>
    </h2>
  </div>
  <main class="px-12 top-[-4rem] relative">
    <RouterView />
  </main>
</template>

<style scoped></style>

// employee-dashboard/src/App.jsx
import logo from '/favicon.svg'
import './App.css'

import { ArrowRightIcon } from '@heroicons/react/24/outline'
import NavButton from './components/NavButton'
import ProfilePicture from './components/ProfilePicture'

function App() {

  return (
    <>
    <div className="bg-blue-100 px-12 flex justify-between items-center">
      <div className="flex justify-between items-centre">
        <img src={logo} alt="logo" className='h-12 my-2' />
      </div>
      <div className="flex gap-6 5 self-stretch py-2">
        <NavButton label="Dashboard" to="#" />
        <NavButton label="Stats" to="#" />
        <NavButton label="My Requests" to="#" />
        <NavButton label="Report" to="#" />
      </div>
      <div>
        <ProfilePicture />
      </div>
    </div>

    {/* second dash area  */}
    <div className="bg-blue-200 h-[190px]">
      <div className="py-4 px-12 flex justify-between">
        <h4 className="text-4xl font-semibold flex justify-between w-full mt-4">
          <span>Good morning, Mary ☕</span>
          <button className="bg-blue-500 text-white flex gap-2 items-center px-3 py-2 font-normal text-xl rounded-md cursor-pointer hover:bg-blue-600"><ArrowRightIcon className='size-6' /> Request leave</button>
        </h4>
      </div>
    </div>

    </>
  )
}

export default App
